# Generated by Django 6.0.7 on 2026-07-25 23:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_stream_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
